// Code generated by "stringer -type=mode"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[initiative-0]
	_ = x[battle-1]
	_ = x[input-2]
}

const _mode_name = "initiativebattleinput"

var _mode_index = [...]uint8{0, 10, 16, 21}

func (i mode) String() string {
	if i >= mode(len(_mode_index)-1) {
		return "mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mode_name[_mode_index[i]:_mode_index[i+1]]
}
